"""
Orione build (-D CC_ORIONE) only: the web interface is the single file frontend-orione/index.html plus
manifest, icons and fonts (frontend-orione/assets.py). They are compiled into the firmware
(OrioneWebAssets.h in the build folder, served from flash by src/flashAssets.h) instead of LittleFS:
a file from LittleFS cost up to ~18 KB of heap and most of the web server's stack per request
(measured 08.10.2026), and an update is now one firmware for page and logic alike.

data/ (the LittleFS image) stays empty apart from config.json when orione_deploy.py or a USB setup
passes the machine's settings in ORIONE_FS_CONFIG; it replaces what the stock frontend scripts wrote.
"""

Import("env")  # noqa: F821  (PlatformIO)

import gzip
import hashlib
import io
import os
import shutil
import sys

TYPES = {".html": "text/html; charset=utf-8", ".json": "application/manifest+json", ".png": "image/png", ".woff2": "font/woff2"}
# the page is asked for every time (304 while unchanged); a font gets a new name when it changes
CACHE = {".html": "no-cache", ".woff2": "max-age=31536000, immutable"}


def header(files):
    """C++ header with the files as byte arrays in flash: files = [(url, name, content, gzipped)]"""
    out = ["// generated by orione_frontend.py from frontend-orione/: do not edit", "#pragma once", "#include <Arduino.h>", "",
           "namespace orione_web {", "",
           "    struct Asset {", "            const char* url;", "            const char* type;", "            const uint8_t* data;",
           "            size_t size;", "            bool gzip;", "            const char* etag;", "            const char* cache;", "    };", ""]
    rows = []
    for i, (url, name, content, gz) in enumerate(files):
        ext = os.path.splitext(name)[1]
        etag = '\\"' + hashlib.sha1(content).hexdigest()[:16] + '\\"'
        out.append(f"    static const uint8_t kData{i}[] PROGMEM = {{")
        for k in range(0, len(content), 24):
            out.append("        " + ",".join(str(b) for b in content[k:k + 24]) + ",")
        out.append("    };")
        rows.append(f'        {{"{url}", "{TYPES[ext]}", kData{i}, {len(content)}, {"true" if gz else "false"}, "{etag}", "{CACHE.get(ext, "max-age=604800")}"}},')
    out += ["", "    inline constexpr Asset kAssets[] = {"] + rows + ["    };", "", "} // namespace orione_web", ""]
    return "\n".join(out)


if "CC_ORIONE" in " ".join(env.GetProjectOption("build_flags", [])):  # noqa: F821  (CPPDEFINES are not parsed yet in pre: scripts)
    root = env.subst("$PROJECT_DIR")  # noqa: F821
    source = os.path.join(root, "frontend-orione", "index.html")

    with open(source, "rb") as f:
        raw = f.read()

    packed = io.BytesIO()
    with gzip.GzipFile(fileobj=packed, mode="wb", compresslevel=9, mtime=0) as gz:  # mtime 0: same bytes, same ETag
        gz.write(raw)

    sys.path.insert(0, os.path.join(root, "frontend-orione"))
    import assets  # noqa: E402

    files = [("/", "index.html", packed.getvalue(), True)] + [("/" + name, name, content, False) for name, content in sorted(assets.files().items())]
    folder = os.path.join(env.subst("$BUILD_DIR"), "orione_web")  # noqa: F821
    os.makedirs(folder, exist_ok=True)
    target = os.path.join(folder, "OrioneWebAssets.h")
    text = header(files)

    if not os.path.exists(target) or open(target).read() != text:  # unchanged: no rebuild of the web server
        with open(target, "w") as f:
            f.write(text)

    env.Append(CPPPATH=[folder])  # noqa: F821
    print(f"Orione frontend: {len(files)} files into the firmware ({sum(len(c) for _, _, c, _ in files)} bytes, page {len(raw)} -> {len(packed.getvalue())})")

    # LittleFS image: only the settings, if given (orione_deploy.py, USB setup); otherwise empty
    data = os.path.join(root, "data")
    shutil.rmtree(data, ignore_errors=True)
    os.makedirs(data)
    keep = os.environ.get("ORIONE_FS_CONFIG")
    if keep:
        shutil.copyfile(keep, os.path.join(data, "config.json"))
        print(f"Orione frontend: settings of the machine into the filesystem image ({os.path.getsize(keep)} bytes)")
