#!/usr/bin/env python3
"""
Generate an anti-aliased bitmap font for rd::Font (RoundDisplayFont.h) from a TTF and write
it as a C header.

Format (little endian):
  header   8 bytes   'R' 'D' version=1 size ascent descent glyph_count(u16)
  glyphs  10 bytes   code(u16) width height advance left(i8) top(i8) offset(u24), sorted by code
  bitmaps            4 bit coverage per pixel, two pixels per byte (high nibble first), rows
                     one after another; every glyph starts on a new byte at its offset
                     (counted from the end of the glyph table)

Compared with the VLW format (28 byte glyph records, 8 bit coverage) this needs about half the
flash; 16 coverage levels look the same on the 240x240 panel.

Only the characters that are actually needed are converted. Digits can be made tabular (all the
same advance width), so numbers that change constantly do not jitter horizontally.

Requires: pip install freetype-py

Example:
  make_font.py --ttf fonts/BarlowSemiCondensed-Medium.ttf --size 80 \
      --chars "0123456789,.-" --tabular --name rd_font_big --out src/fonts/fontBig.h
"""

import argparse
import struct
import sys

import freetype

PRESETS = {
    "ascii": "".join(chr(c) for c in range(0x20, 0x7F)),
    "de": "ÄÖÜäöüß°·–",
}


def expand_chars(spec):
    out = []
    for part in spec:
        if part.startswith("@"):
            out.append(PRESETS[part[1:]])
        else:
            out.append(part)
    return sorted(set("".join(out)) | {" "}, key=ord)


def render_glyph(face, ch):
    face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_LIGHT)
    g = face.glyph
    bm = g.bitmap
    w, h = bm.width, bm.rows
    coverage = []
    for row in range(h):
        start = row * bm.pitch
        coverage.extend(bm.buffer[start:start + w])
    return {
        "code": ord(ch),
        "w": w,
        "h": h,
        "adv": (g.advance.x + 32) >> 6,
        "dx": g.bitmap_left,
        "dy": g.bitmap_top,
        "coverage": coverage,
    }


def pack4(coverage):
    levels = [(a * 15 + 127) // 255 for a in coverage]
    if len(levels) % 2:
        levels.append(0)
    return bytes(levels[i] << 4 | levels[i + 1] for i in range(0, len(levels), 2))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--size", type=int, required=True, help="pixel size (em height)")
    ap.add_argument("--chars", action="append", required=True, help="characters, or @ascii / @de presets; may repeat")
    ap.add_argument("--tabular", action="store_true", help="give all digits the same advance width")
    ap.add_argument("--tracking", type=int, default=0, help="extra advance in pixels for every glyph")
    ap.add_argument("--name", required=True, help="C identifier of the array")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    face = freetype.Face(args.ttf)
    face.set_pixel_sizes(0, args.size)

    glyphs = []
    for ch in expand_chars(args.chars):
        if face.get_char_index(ch) == 0 and ch != " ":
            sys.exit(f"character {ch!r} (U+{ord(ch):04X}) is missing in {args.ttf}")
        if ord(ch) > 0xFFFF:
            sys.exit(f"character U+{ord(ch):04X} is outside the basic plane")
        glyphs.append(render_glyph(face, ch))

    if args.tabular:
        digits = [g for g in glyphs if chr(g["code"]).isdigit()]
        width = max(g["adv"] for g in digits)
        for g in digits:
            g["dx"] += (width - g["adv"]) // 2
            g["adv"] = width

    for g in glyphs:
        g["adv"] += args.tracking
        if g["adv"] > 255 or g["w"] > 255 or g["h"] > 255 or not -128 <= g["dx"] <= 127 or not -128 <= g["dy"] <= 127:
            sys.exit(f"glyph U+{g['code']:04X} too large for the format")

    ascent = face.size.ascender >> 6
    descent = -(face.size.descender >> 6)

    table = bytearray()
    bitmaps = bytearray()
    for g in glyphs:
        offset = len(bitmaps)
        table += struct.pack("<HBBBbb", g["code"], g["w"], g["h"], g["adv"], g["dx"], g["dy"])
        table += struct.pack("<I", offset)[:3]
        bitmaps += pack4(g["coverage"])

    if len(bitmaps) >= 1 << 24:
        sys.exit("font too large")

    blob = bytearray(b"RD") + struct.pack("<BBBBH", 1, args.size, ascent, descent, len(glyphs)) + table + bitmaps

    chars = "".join(chr(g["code"]) for g in glyphs)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("// Generated by lib/RoundDisplay/tools/make_font.py - do not edit.\n")
        f.write(f"// Font: {args.ttf.split('/')[-1]} ({face.family_name.decode()}), {args.size} px, SIL Open Font License 1.1\n")
        f.write(f"// Glyphs ({len(glyphs)}): {chars!r}\n")
        f.write(f"// Size: {len(blob)} bytes\n\n")
        f.write("#pragma once\n\n#include <cstdint>\n\n")
        f.write(f"const uint8_t {args.name}[] = {{\n")
        for i in range(0, len(blob), 24):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in blob[i:i + 24]) + ",\n")
        f.write("};\n")

    print(f"{args.out}: {len(glyphs)} glyphs, {len(blob)} bytes")


if __name__ == "__main__":
    main()
