#!/usr/bin/env python3
"""
Generate an anti-aliased VLW font (Processing / TFT_eSPI / LovyanGFX format) from a TTF
and write it as a C header.

Only the characters that are actually needed are converted, which keeps the flash
footprint small. Digits can be made tabular (all the same advance width), so numbers
that change constantly do not jitter horizontally.

Requires: pip install freetype-py

Example:
  make_vlw_font.py --ttf fonts/BarlowSemiCondensed-Medium.ttf --size 72 \
      --chars "0123456789,.-" --tabular --name rd_font_big --out src/fonts/fontBig.h
"""

import argparse
import struct
import sys

import freetype

PRESETS = {
    "ascii": "".join(chr(c) for c in range(0x20, 0x7F)),
    "de": "ÄÖÜäöüß°·–",
}


def expand_chars(spec):
    out = []
    for part in spec:
        if part.startswith("@"):
            out.append(PRESETS[part[1:]])
        else:
            out.append(part)
    chars = sorted(set("".join(out)) | {" "}, key=ord)
    return chars


def render_glyph(face, ch):
    face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_LIGHT)
    g = face.glyph
    bm = g.bitmap
    w, h = bm.width, bm.rows
    data = bytearray()
    for row in range(h):
        start = row * bm.pitch
        data.extend(bm.buffer[start:start + w])
    return {
        "code": ord(ch),
        "w": w,
        "h": h,
        "adv": (g.advance.x + 32) >> 6,
        "dx": g.bitmap_left,
        "dy": g.bitmap_top,
        "bitmap": bytes(data),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--size", type=int, required=True, help="pixel size (em height)")
    ap.add_argument("--chars", action="append", required=True, help="characters, or @ascii / @de presets; may repeat")
    ap.add_argument("--tabular", action="store_true", help="give all digits the same advance width")
    ap.add_argument("--tracking", type=int, default=0, help="extra advance in pixels for every glyph")
    ap.add_argument("--name", required=True, help="C identifier of the array")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    face = freetype.Face(args.ttf)
    face.set_pixel_sizes(0, args.size)

    glyphs = []
    for ch in expand_chars(args.chars):
        if face.get_char_index(ch) == 0 and ch != " ":
            sys.exit(f"character {ch!r} (U+{ord(ch):04X}) is missing in {args.ttf}")
        glyphs.append(render_glyph(face, ch))

    if args.tabular:
        digits = [g for g in glyphs if chr(g["code"]).isdigit()]
        width = max(g["adv"] for g in digits)
        for g in digits:
            g["dx"] += (width - g["adv"]) // 2
            g["adv"] = width

    for g in glyphs:
        g["adv"] += args.tracking
        if g["adv"] > 255 or g["w"] > 255 or not -128 <= g["dx"] <= 127:
            sys.exit(f"glyph U+{g['code']:04X} too large for the VLW format")

    ascent = face.size.ascender >> 6
    descent = -(face.size.descender >> 6)

    blob = bytearray()
    blob += struct.pack(">6i", len(glyphs), 11, args.size, 0, ascent, descent)
    for g in glyphs:
        blob += struct.pack(">7i", g["code"], g["h"], g["w"], g["adv"], g["dy"], g["dx"], 0)
    for g in glyphs:
        blob += g["bitmap"]

    chars = "".join(chr(g["code"]) for g in glyphs)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("// Generated by lib/RoundDisplay/tools/make_vlw_font.py - do not edit.\n")
        f.write(f"// Font: {args.ttf.split('/')[-1]} ({face.family_name.decode()}), {args.size} px, SIL Open Font License 1.1\n")
        f.write(f"// Glyphs ({len(glyphs)}): {chars!r}\n")
        f.write(f"// Size: {len(blob)} bytes\n\n")
        f.write("#pragma once\n\n#include <cstdint>\n\n")
        f.write(f"const uint8_t {args.name}[] = {{\n")
        for i in range(0, len(blob), 24):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in blob[i:i + 24]) + ",\n")
        f.write("};\n")

    print(f"{args.out}: {len(glyphs)} glyphs, {len(blob)} bytes")


if __name__ == "__main__":
    main()
